import google.generativeai as genai

# -----------------------------------------------------------
# Learning Path Recommendation Module
#
# Generates a structured learning roadmap for a topic
# using the Gemini model.
# -----------------------------------------------------------

# Create the Gemini model once when the application starts
model = genai.GenerativeModel(
    model_name="models/gemini-3.5-flash"
)


def get_learning_recommendations(topic: str) -> str:
    """
    Generates a structured learning path for a given topic.

    Parameters:
        topic (str): Topic the student wants to learn.

    Returns:
        str: Learning roadmap generated by Gemini.
    """

    try:

        # Prevent empty topics
        if not topic or not topic.strip():
            return "Please enter a valid topic."

        # Educational learning-path prompt
        prompt = f"""
        You are an AI Educational Tutor.

        Create a structured learning roadmap for:

        Topic: {topic}

        Include:

        1. Beginner Level
           - Fundamental concepts
           - Basic skills to learn

        2. Intermediate Level
           - Topics to study next
           - Practical exercises

        3. Advanced Level
           - Advanced concepts
           - Real-world applications

        4. Recommended Learning Order

        5. Suggested Resources
           - Books
           - Online courses
           - Practice activities

        Keep the roadmap clear, organized, and beginner-friendly.
        """

        # Generate learning recommendations
        response = model.generate_content(prompt)

        # Extract text safely
        if hasattr(response, "text") and response.text:
            return response.text.strip()

        if hasattr(response, "parts") and response.parts:
            return response.parts[0].text

        return "Could not generate a learning roadmap."

    except Exception as e:
        return f"Error in Learning Path Module: {str(e)}"


