import google.generativeai as genai

# -----------------------------------------------------------
# Gemini Q&A Module
#
# This module is responsible for answering user questions
# using the Gemini model.
#
# The model is loaded once when the application starts,
# which is more efficient than creating it for every request.
# -----------------------------------------------------------

# Create the Gemini model once
model = genai.GenerativeModel(
    model_name="models/gemini-3.5-flash"
)


def answer_question_with_gemini(question: str) -> str:
    """
    Generates an educational answer for a user's question.

    Parameters:
        question (str): The question entered by the user.

    Returns:
        str: The answer generated by Gemini or an error message.
    """

    try:
        # Prevent empty questions from being sent to Gemini
        if not question or not question.strip():
            return "Please enter a valid question."

        # Educational prompt to make responses clearer
        prompt = f"""
        You are an AI Educational Assistant.

        Your job is to:
        - Answer accurately.
        - Use simple and clear language.
        - Explain concepts in a beginner-friendly way.
        - Keep responses concise but informative.

        Question:
        {question}
        """

        # Send the prompt to Gemini
        response = model.generate_content(prompt)

        # Ensure a response was actually generated
        if hasattr(response, "text") and response.text:
            return response.text.strip()

        return "No response was generated."

    except Exception as e:
        # Catch unexpected errors and return a readable message
        return f"Error in Q&A module: {str(e)}"

